# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-11-22 16:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='course4',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(default=b'', max_length=1000)),
                ('description', models.TextField(default=b'', max_length=1000)),
                ('variable', models.TextField(default=b'', max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='course4_attribute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_name', models.CharField(default=b'', max_length=30)),
                ('lesson_introduction', models.TextField(default=b'', max_length=255)),
                ('lesson', models.CharField(default=b'', max_length=30)),
                ('user_id', models.ManyToManyField(default=b'', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='course4_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default=b'', max_length=20)),
                ('ch', models.CharField(default=b'', max_length=20)),
                ('part', models.CharField(default=b'', max_length=20)),
                ('name', models.CharField(default=b'', max_length=20)),
                ('comparison', jsonfield.fields.JSONField(blank=True, default=b'', null=True)),
                ('answer', models.TextField(default=b'', max_length=10000)),
                ('course_attribute', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='htmlapp.course4_attribute')),
            ],
        ),
        migrations.CreateModel(
            name='course_user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(default=b'', max_length=1000)),
                ('coursename', models.CharField(default=b'', max_length=20)),
                ('correct', models.BooleanField(default=False)),
                ('lesson', models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='htmlapp.course4_attribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Introduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sef', models.TextField(max_length=255)),
                ('lesson', models.ManyToManyField(blank=True, to='htmlapp.course4_attribute')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='course4',
            name='ch',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='htmlapp.course4_detail'),
        ),
        migrations.AddField(
            model_name='course4',
            name='course_attribute_id',
            field=models.ForeignKey(default=b'', on_delete=django.db.models.deletion.CASCADE, to='htmlapp.course4_attribute'),
        ),
    ]
